name: data_yeeter_flutter
description: A university project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  go_router: ^5.1.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
